import { Dialog, Input, Button } from "@cloudflare/kumo";
import { GitHubIcon } from "@/components/ui/GitHubIcon";
import { Loader2, X } from "lucide-react";
import { useState } from "react";

interface GeneratedProject {
  projectName: string;
  files: Array<{ path: string; content: string }>;
}

interface ExportGitHubModalProps {
  project: GeneratedProject;
  onClose: () => void;
}

export function ExportGitHubModal({
  project,
  onClose,
}: ExportGitHubModalProps) {
  const [repoName, setRepoName] = useState(
    project.projectName.toLowerCase().replace(/\s+/g, "-"),
  );
  const [isPrivate, setIsPrivate] = useState(false);
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">(
    "idle",
  );
  const [resultUrl, setResultUrl] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleCreate = async () => {
    setStatus("loading");
    setErrorMsg(null);
    try {
      const { api } = await import("@/lib/api.js");
      try {
        const res = await api.unwrap<{ repoUrl: string }>(
          "/github/create-repo",
          {
            method: "POST",
            body: JSON.stringify({
              name: repoName,
              description: `Generated by MagicAppDev — ${project.projectName}`,
              isPrivate,
              files: project.files,
            }),
          },
        );
        setResultUrl(res.repoUrl ?? null);
        setStatus("done");
      } catch (err) {
        setErrorMsg(err instanceof Error ? err.message : "Unknown error");
        setStatus("error");
      }
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Unknown error");
      setStatus("error");
    }
  };

  return (
    <Dialog.Root open onOpenChange={open => !open && onClose()}>
      <Dialog size="lg" className="p-6 space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <Dialog.Title className="flex items-center gap-2 text-white">
              <GitHubIcon className="w-5 h-5 text-white" />
              Export to GitHub
            </Dialog.Title>
            <Dialog.Description className="text-sm text-zinc-400">
              Create a GitHub repository for{" "}
              <span className="font-medium text-zinc-100">
                {project.projectName}
              </span>{" "}
              and push all{" "}
              <span className="font-medium text-zinc-100">
                {project.files.length} files
              </span>
              .
            </Dialog.Description>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-zinc-500 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {status === "done" && resultUrl ? (
          <div className="bg-green-900/30 border border-green-700/50 rounded-xl p-4 space-y-2">
            <p className="text-sm font-semibold text-green-300">
              ✓ Repository created!
            </p>
            <a
              href={resultUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-green-400 underline break-all"
            >
              {resultUrl}
            </a>
          </div>
        ) : (
          <>
            <Input
              label="Repository Name"
              value={repoName}
              onChange={e => setRepoName(e.target.value)}
              placeholder="my-awesome-app"
              disabled={status === "loading"}
            />

            <label className="flex items-center gap-2 text-sm text-zinc-300 cursor-pointer">
              <input
                type="checkbox"
                checked={isPrivate}
                onChange={e => setIsPrivate(e.target.checked)}
                className="rounded border-zinc-600"
                disabled={status === "loading"}
              />
              Make repository private
            </label>

            {errorMsg && (
              <p className="text-sm text-red-400 bg-red-900/20 border border-red-800/40 rounded-lg px-3 py-2">
                {errorMsg}
              </p>
            )}

            <div className="bg-zinc-800/60 rounded-xl p-4 border border-zinc-700/50">
              <p className="text-[11px] font-bold uppercase tracking-wider text-zinc-500 mb-2">
                Manual alternative
              </p>
              <pre className="text-xs text-green-400 bg-black/60 rounded-lg p-3 overflow-x-auto leading-relaxed">
                {`cd ${repoName || "my-app"}\ngit init && git add .\ngit commit -m "Initial commit"\ngh repo create ${repoName || "my-app"} --public --push --source=.`}
              </pre>
            </div>
          </>
        )}

        <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
          <Button variant="secondary" onClick={onClose}>
            {status === "done" ? "Close" : "Cancel"}
          </Button>
          {status !== "done" && (
            <Button
              variant="primary"
              icon={
                status === "loading" ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <GitHubIcon className="w-4 h-4" />
                )
              }
              onClick={handleCreate}
              disabled={status === "loading" || !repoName.trim()}
            >
              {status === "loading" ? "Creating…" : "Create on GitHub"}
            </Button>
          )}
        </div>
      </Dialog>
    </Dialog.Root>
  );
}
