packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@swc/core"
  - canvas
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@conventional-changelog/git-client@<2.0.0": ">=2.0.0"
  ai@<5.0.52: ">=5.0.52"
  esbuild@<=0.24.2: ">=0.25.0"
  jsondiffpatch@<0.7.2: ">=0.7.2"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  tar@<=7.5.3: ">=7.5.4"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"
  wrangler@>=4.0.0 <4.59.1: ">=4.59.1"
