<arg_value>name: Bug Report
description: Report a bug to help us improve the project
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      description: The operating system you're using
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment-browser
    attributes:
      label: Browser / Environment
      description: The browser or environment where the bug occurs
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Node.js
        - React Native
        - Expo
        - Other
    validations:
      required: true

  - type: input
    id: environment-version
    attributes:
      label: Version
      description: Version of the browser, environment, or package
      placeholder: e.g., Chrome 120.0.6099, Node.js 18.17.0, v2.4.1
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or error logs to help explain your problem
      placeholder: |
        ![Screenshot description](link-to-screenshot)

        ```
        Error logs here...
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the Contributing Guidelines
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
